### ISSUE TITLE
Can't build fastcomp with gcc 8 on Fedora 28

### ISSUE THREAD

**Issue by brion** [juj/emsdk#144]
There's an upstream bug in LLVM 5.0 which [prevents compilation on gcc 8](https://bugzilla.redhat.com/show_bug.cgi?id=1540620), which is the default in Fedora 28:

```
In file included from /home/brion/src/emsdk-portable/clang/fastcomp/src/tools/lli/lli.cpp:30:
/home/brion/src/emsdk-portable/clang/fastcomp/src/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h: In member function ‘llvm::Expected<std::vector<char> > llvm::orc::remote::OrcRemoteTargetClient<ChannelT>::readMem(char*, llvm::JITTargetAddress, uint64_t)’:
/home/brion/src/emsdk-portable/clang/fastcomp/src/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h:722:26: error: could not convert ‘((llvm::orc::remote::OrcRemoteTargetClient<ChannelT>*)this)->callB<llvm::orc::remote::OrcRemoteTargetRPCAPI::ReadMem>(Src, Size)’ from ‘Expected<vector<unsigned char,allocator<unsigned char>>>’ to ‘Expected<vector<char,allocator<char>>>’
     return callB<ReadMem>(Src, Size);
            ~~~~~~~~~~~~~~^~~~~~~~~~~
```

The patch attached on that Red Hat bug appears to work when applied locally to the fastcomp source checkout and then re-running `emsdk install incoming-64bit`: https://bugzilla.redhat.com/attachment.cgi?id=1389687

Supposedly it's fixed upstream on LLVM 6.0.

**Comment by kripken** [comment]
We could cherry-pick the LLVM 6 fix to fastcomp, if that would be useful.

**Comment by brion** [comment]
Yeah, I think that'll resolve it nicely.

**Comment by kripken** [comment]
The upstream change appears to be 30e9aa60fea44210ac8d843d2f6a4b3bd2578bf4 which contains a lot more than this fix. So we could just do the trivial `char=>uint8_t` change ourselves, but that does mean it'll show up as a merge error next time we try to merge upstream.

Maybe that's not so bad. But another option is to try to work on merging 6.0 anyhow.

**Comment by kripken** [comment]
I opened `next-merge` branches in the 3 repos, did some initial work to get the repos to compile after the merge.

**Comment by brion** [comment]
Awesome! Didn't realize we were getting that close to merging LLVM 6. :)

**Comment by brion** [comment]
Can confirm that the new-merge branch with 6.0.1 builds on Fedora 28.

**Comment by brion** [comment]
I can confirm that I can build sdk-incoming-64bit on Fedora 28 now. Can close out. :)
