### PR TITLE
Fixed #148 - unable to compile sdk-incoming on linux

### LINKED ISSUE #148: Unable to compile incoming after  #145
Hi,
After #145 was merged I started to observe error in binaryen compilation: 
Executed command: 
```
./emsdk install --build=MinSizeRel sdk-incoming-64bit -j8
```

Result:
```
[100%] Linking CXX executable optimizer
[100%] Built target optimizer
Done installing tool 'emscripten-incoming-64bit'.
Manifest error: No tool by name 'binaryen-incoming-64bit' found! This may indicate an internal SDK error!
Traceback (most recent call last):
  File "./emsdk", line 2350, in <module>
    sys.exit(main())
  File "./emsdk", line 2333, in main
    success = tool.install()
  File "./emsdk", line 1337, in install
    success = tool.install()
AttributeError: 'NoneType' object has no attribute 'install'
```

Moreover after `emsdk list`
```
...
The following SDKs can be compiled from source:
         sdk-incoming-32bit       
Manifest error: No tool by name 'binaryen-incoming-64bit' found! This may indicate an internal SDK error!
Manifest error: No tool by name 'binaryen-incoming-64bit' found! This may indicate an internal SDK error!
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         
         sdk-tag-1.38.5-32bit     
```

Issue was introduced by 16125272b28ba8a6a65ddde81924aa894d65080b

CC:
@jgravelle-google

### PR DESCRIPTION
**Pull request by asRIA**
An attempt to fix problem with compiling emscripten with command: 
```
./emsdk install sdk-incoming-64bit -
```

### CODE REVIEW

**Comment by asRIA** [comment]
Closing in favor of #150
